# Absolutely essential: we must build using VS 2019.
os: Visual Studio 2019

branches:
  only:
  - master


build_script:
  - cmd: date /t
  - cmd: time /t
  - cmd: tzutil /g
  - cmd: set
  - cmd: MSBuild.exe /t:restore /p:Configuration=Debug /v:quiet AntlrVSIX.sln
  - cmd: MSBuild.exe /p:Configuration=Debug /v:normal AntlrVSIX.sln
  - cmd: cd VsCode
  - cmd: install-cmd.bat
  - cmd: cd ..

test_script:
  - cmd: cd UnitTestProject1
  - cmd: dotnet test

artifacts:
  - path: '**\*.vsix'
